/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./views/cart/index.vue')['default']
    Category: typeof import('./views/category/index.vue')['default']
    Detail: typeof import('./views/detail/index.vue')['default']
    DetailHot: typeof import('./views/detail/components/DetailHot.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GoodsItem: typeof import('./views/home/components/GoodsItem.vue')['default']
    Home: typeof import('./views/home/index.vue')['default']
    HomeBanner: typeof import('./views/home/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./views/home/components/HomeCategory.vue')['default']
    HomeHot: typeof import('./views/home/components/HomeHot.vue')['default']
    HomeNew: typeof import('./views/home/components/HomeNew.vue')['default']
    HomePanel: typeof import('./views/home/components/HomePanel.vue')['default']
    HomeProduct: typeof import('./views/home/components/HomeProduct.vue')['default']
    ImageView: typeof import('./components/image-view/index.vue')['default']
    Layout: typeof import('./views/layout/index.vue')['default']
    LayoutCart: typeof import('./views/layout/components/LayoutCart.vue')['default']
    LayoutFixed: typeof import('./views/layout/components/LayoutFixed.vue')['default']
    LayoutFooter: typeof import('./views/layout/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./views/layout/components/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./views/layout/components/LayoutNav.vue')['default']
    Login: typeof import('./views/login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategory: typeof import('./views/sub-category/index.vue')['default']
    XtxSku: typeof import('./components/XtxSku/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
