/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof import('./views/category/index.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    Home: typeof import('./views/home/index.vue')['default']
    HomeBanner: typeof import('./views/home/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./views/home/components/HomeCategory.vue')['default']
    HomeHot: typeof import('./views/home/components/HomeHot.vue')['default']
    HomeNew: typeof import('./views/home/components/HomeNew.vue')['default']
    HomeProduct: typeof import('./views/home/components/HomeProduct.vue')['default']
    Layout: typeof import('./views/layout/index.vue')['default']
    LayoutFixed: typeof import('./views/layout/components/LayoutFixed.vue')['default']
    LayoutFooter: typeof import('./views/layout/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./views/layout/components/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./views/layout/components/LayoutNav.vue')['default']
    Login: typeof import('./views/login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseCategory: typeof import('./stores/useCategory.ts')['default']
  }
}
